menu:
  Index:
    url: /
    External: false
    name: ğŸ“„é¦–é¡µ
  Tags:
    url: /tags.html
    External: false
    name: ğŸ§¾æ ‡ç­¾
  Categories:
    url: /categories.html
    External: false
    name: ğŸ—ƒï¸åˆ†ç±»
  About:
    url: /about.html
    External: false
    name: ğŸ¤“å…³äº
  Hemo:
    url: https://i.mengze.vip
    External: true
    name: ğŸ ä¸»é¡µ
    

# æ·±è‰²ä¸»é¢˜
dark_theme:
  enable: false
  mode: auto # å¯é€‰ autoã€dark

# è”ç³»æ–¹å¼
contact:
  github: "https://github.com/YShenZe"
  twitter:
  weibo:
  zhihu:
  facebook:
  email: administrator@yzeblog.dev.tc

# é¦–é¡µå¤´åƒå›¾ç‰‡
avatar: https://cdn.mengze.vip/gh/YShenZe/Blog-Static-Resource@main/images/1f94e9c693374150b1f8dfd8de0fcce1.jpeg

# ç«™ç‚¹å›¾æ ‡
favicon: https://cdn.mengze.vip/gh/YShenZe/Blog-Static-Resource@main/images/1f94e9c693374150b1f8dfd8de0fcce1.jpeg

# è°·æ­Œç»Ÿè®¡ è·Ÿè¸ª ID
ga:

# ç™¾åº¦ç»Ÿè®¡ The baidu web analytics
baidu_tongji:

comment:
  enable: false
  system: gitalk # å¯é€‰ gitalkã€twikoo
  config:
    gitalk:
      clientId: Ov23liKLpa1lEhX2o6aV
      clientSecret: 8a676c78dec97d0d2aadd353f6a48d66d72de852
      repository: Netlify-Hexo-Blog # ä»“åº“å
      owner: YShenZe # ä»“åº“æ‰€æœ‰è€…
      createIssueManually: true # å¦‚æœå½“å‰é¡µé¢æ²¡æœ‰ç›¸åº”çš„ isssue ä¸”ç™»å½•çš„ç”¨æˆ·å±äº adminï¼Œåˆ™ä¼šè‡ªåŠ¨åˆ›å»º issueã€‚å¦‚æœè®¾ç½®ä¸º trueï¼Œåˆ™æ˜¾ç¤ºä¸€ä¸ªåˆå§‹åŒ–é¡µé¢ï¼Œåˆ›å»º issue éœ€è¦ç‚¹å‡» init æŒ‰é’®ã€‚
    twikoo:
      envId: https://twkio.mengze.vip/
      region: ap-shanghai
      mark: # ä¸€ä¸ªtwikooæœåŠ¡ç«¯åº”ç”¨äºå¤šä¸ªå†…å®¹æ—¶ï¼Œå¯å¡«å†™æ­¤é¡¹

# åº•éƒ¨é“¾æ¥
bottom_link:
  rss:
    url: /rss2.xml
    text: RSS
  home:
    url: https://i.mengze.vip/
    text: Home Page

# åº•éƒ¨æ˜¾ç¤ºæ¥æºä¿¡æ¯
bottom_source:
  enable: true

# è„šæ³¨
footnote:
  enable: true # æ˜¯å¦å¼€å¯è„šæ³¨è§£æ
  ignoreCodeBlock: false # æ˜¯å¦å¿½ç•¥ä»£ç å—ä¸­çš„è„šæ³¨

# å›¾ç‰‡é…ç½®
image:
  lazyload_enable: true # å›¾ç‰‡æ‡’åŠ è½½
  lazyload_placeholder: # å›¾ç‰‡æ‡’åŠ è½½å ä½å›¾
  photo_zoom: simple-lightbox # å¯é€‰ simple-lightboxã€fancyboxã€false(ç¦ç”¨)

# cdn é…ç½®
cdn:
  enable: false
  # CDN æä¾›è€…
  provider: jsdelivr # å¯é€‰ jsdelivrã€unpkgã€bootcdn